name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # # Add platform-specific ffmpeg installation
      # - name: Install Dependencies
      #   run: |
      #     if [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
      #       brew install ffmpeg
      #     elif [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
      #       sudo apt-get update
      #       sudo apt-get install -y ffmpeg wine
      #     elif [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
      #       choco install ffmpeg
      #     fi

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build for Platform
        run: |
          case "${{ matrix.os }}" in
            macos-latest)
              chmod +x make_icon.sh
              npm run build:mac
              ;;
            windows-latest)
              npm run build:win
              ;;
            ubuntu-latest)
              chmod +x make_icon.sh
              npm run build:linux
              ;;
          esac

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.dmg
            dist/**/*.AppImage
            dist/**/*.exe